apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: application
  namespace: app
spec:
  selector:
    matchLabels:
      app: application
  replicas: 1
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: apa-admin
        image: asia.gcr.io/hyperlocal-286805/application:1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: apa-admin
  namespace: app
spec:
  selector:
    app: application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
