apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: application
  namespace: app
spec:
  selector:
    matchLabels:
      app: application
  replicas: 1
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application
        image: gcr.io/majorproject-313305/github.com/generic-matrix/programming-langugages-api
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: app
spec:
  type: LoadBalancer
  selector:
    app: application
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
